name: Static Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Install Psalm
        run: composer bin tools require --dev vimeo/psalm

      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github --no-progress

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Install PHPStan
        run: composer bin tools require --dev phpstan/phpstan

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --error-format=github --no-progress --memory-limit=512M
